### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by gzimmers**
Never worked with vue or electron, so still getting a feel for things. But I figured adding themes would be pretty easy. It's almost done. Let me know if you're interested in using this. Otherwise I'll just trash it.

Though if you are interested, I'll resolve the conflicts and finish it up. If that is the case, I have a question or two for you.

### CODE REVIEW

**Comment by mtobeiyf** [comment]
Thank you very much. 👍 
You can still work on this. A theme system would be great! 

There are several problems need to be taken care:
- I've replaced `settingsStore.js` with `configStore` and moved it to the `main` directory.
- Settings should be saved in the main process (main.js). You can check how the locale setting is saved. Communication between renderer and main process should be established.
- The theme system should be hackable, which means users can further customize the details like color, font, or other appearance in a file like `style.css`.

Thank you. I'm waiting for your modification and PRs.
This would be great.

**Comment by gzimmers** [comment]
Sweet, I'll spend some time finishing it up. 

> The theme system should be hackable, which means users can further customize the details like color, font, or other appearance in a file like style.css.

Totally agree, though I couldn't think of a way to generate a dynamic style.css. If you could point me in the right direction regarding generating a css file dynamically without hacking it to bits, that would be great. But otherwise, I'll continue with my approach of using style objects and v-bind to attach them.

My other question was regarding the TabsPane. I'm having difficulty styling it and I can't seem to figure out where you got the component. If you could refer me to the docs that provided that component so I could read about how to style it, that would be great.

**Comment by mtobeiyf** [comment]
The UI kit for this app is [iview](https://www.iviewui.com/) Check its [components](https://www.iviewui.com/docs/guide/install).
However, [element](http://element.eleme.io/#/en-US) seems more friendly with it's [custom-theme](http://element.eleme.io/#/en-US/component/custom-theme) and larger community. 
I'm a bit want to switch to [element ui](http://element.eleme.io/#/en-US) for next big version.
I'll look into this [theme-building tool](https://github.com/ElementUI/element-theme) or anything similar, I think it will help speed up the procedure of customizing a theme for the contributors.

Besides that, the way I thought is to create a blank `style.css` in the user directory to override the default settings. But I haven't come up with a perfect solution 'cause you have to write them line by line, it's too wearisome.

If you need my help, I could open a new branch named `theme` for your pull request so that I could review and fix something.
Thanks for spending time on this app. If you'd like, we can communicate in private using email or other Instant Message tools. 😄

**Comment by gzimmers** [comment]
Agreed, I emailed you. We can schedule something there.

**Comment by mtobeiyf** [comment]
Ok, I'm gonna close this PR. Check email 😄

**Pull request closed without merging**
